import string
import urllib.request
import json
import unicodedata

def format_hex(str: string):
    return str.replace("#", "").upper()

def format_name(str: string):
    return unicodedata.normalize('NFKD',
           str.replace(" ", ""
             ).replace("(", ""
             ).replace(")", ""
             ).replace("-", ""
             ).replace("/", ""
             ).replace("'", ""
             ).replace("#", ""
             ).replace("&", ""
             ).replace(".", ""
             )
    ).encode('ascii', 'ignore').decode('ascii')

# Load colors data
colors_json = json.loads(urllib.request.urlopen(
                "https://raw.githubusercontent.com/mralexgray/color-names/json/output/colors.json"
              ).read())

# Generate colors list
colors_list = ""
for color in colors_json.values():
    colors_list += f"static constexpr Color {format_name(color['name'])} = hex(0x{format_hex(color['hex'])});\n"

# Generate final C++ code
cpp_code = """// This file was auto-generated by generate_named_colors.py
// Please don't edit the file directly, go to the script!

#pragma once
#include "Color.h"

namespace p6::NamedColor {

%s
} // namespace p6::NamedColor
""" % colors_list

# Write to file
with open('src/NamedColor.h', 'w') as f:
    f.write(cpp_code)